export const FETCH_USER = 'FETCH_USER'
export const LOGOUT = 'LOGOUT'
export const LOGIN_USER = 'LOGIN_USER'

export const FETCH_NOTICE = 'FETCH_NOTICE'
export const FETCH_NEXT_NOTICE = 'FETCH_NEXT_NOTICE'
export const NOTICE_LOADING = 'NOTICE_LOADING'
export const NOTICE_ERROR = "NOTICE_ERROR"

export const FETCH_LECTURE = 'FETCH_LECTURE'
export const FETCH_ONE_LECTURE_DATA = 'FETCH_ONE_LECTURE_DATA'
export const SELECT_LECTURE = 'SELECT_LECTURE'
export const LECTURE_LOADING = 'LECTURE_LOADING'

export const FETCH_MILEAGE = 'FETCH_MILEAGE'
export const MILEAGE_ERROR = 'MILEAGE_ERROR'

export const FETCH_CHAPEL = 'FETCH_CHAPEL'
export const CHAPEL_ERROR = 'CHAPEL_ERROR'
export const SET_IMAGE_NAME = 'SET_IMAGE_NAME'

export const FETCH_EVENTS = 'FETCH_EVENTS'
export const TURN_ON_EVENT_DETAIL = 'TURN_ON_EVENT_DETAIL'
export const TURN_DOWN_EVENT_DETAIL = 'TURN_DOWN_EVENT_DETAIL'
export const SELECT_EVENT = 'SELECT_EVENT'

export const FETCH_CAFETERIA = 'FETCH_CAFETERIA'
export const CAFETERIA_LOADING = 'CAFETERIA_LOADING'

export const TOUCHABLE = 'TOUCHABLE'
export const UNTOUCHABLE = 'UNTOUCHABLE'

export const DECREASE_QRCODE_TIMER = 'DECREASE_QRCODE_TIMER'
export const TURN_ON_EXTENDED_QRCODE = 'TURN_ON_EXTENDED_QRCODE'
export const TURN_DOWN_EXTENDED_QTCODE = 'TURN_DOWN_EXTENDED_QTCODE'
export const INIT_QRCODE = 'INIT_QRCODE'
export const FETCH_QRCODE = 'FETCH_QRCODE'

export const FETCH_TODAYS_PRAYER = 'FETCH_TODAYS_PRAYER'
export const LOADING_PARYER = 'LOADING_PARYER'
export const FETCH_SPECIFIC_PRAYER = 'FETCH_SPECIFIC_PRAYER'